name: KDotH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  host_platforms:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    name: Test ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y cmake

    - name: Update Submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
